# Dependencies
gems:
  - jekyll-sitemap
highlighter:         pygments
markdown:            redcarpet

# Setup
baseurl:             ''
description:         "Tom Zidar senior at University of Michigan. Studying Business & Informatics. fix this"
permalink:           pretty
relative_permalinks: true
sass:
  style:             compressed
tagline:             Tom Zidar's website
title:               tomzidar.com
url:                 http://clarkbk.com

# About
author:
  email:             tzidar@gmail.com
  name:              Tom Zidar
  social_urls:
    facebook:        https://www.facebook.com/tzidar
    github:          https://github.com/tzidar
    linkedin:        https://www.linkedin.com/profile/view?id=160412940&authType=NAME_SEARCH&authToken=3cT-&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A160412940%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1438631346073%2Ctas%3Atom%20zidar
    twitter:         https://twitter.com/tomzidar
    google_plus:     https://plus.google.com/u/0/101356415299525876294
