# Dependencies
gems:
  - jekyll-sitemap
highlighter:         pygments
markdown:            redcarpet

# Setup
baseurl:             ''
description:         "Ben Clark lives in Brooklyn and does marketing at SeatGeek. He's originally from Atlanta, went to school at Vanderbilt, and used to work at Yelp, Clover, Buddy Media, &amp; Salesforce.com."
permalink:           pretty
relative_permalinks: true
sass:
  style:             compressed
tagline:             Tom Zidar's website
title:               tomzidar.com
url:                 http://clarkbk.com

# About
author:
  email:             tzidar@gmail.com
  name:              Tom Zidar
  social_urls:
    facebook:        https://www.facebook.com/tzidar
    github:          https://github.com/tzidar
    linkedin:        https://www.linkedin.com/in/tzidar
    twitter:         https://twitter.com/tomzidar
    google_plus:     https://plus.google.com/u/0/101356415299525876294
