# Dependencies
gems:
  - jekyll-sitemap
highlighter:         rouge
markdown:            kramdown

# Setup
baseurl:             ''
description:         "Tom Zidar works at at Uber"
permalink:           pretty

sass:
  style:             compressed
tagline:             Tom Zidar's website
title:               tomzidar.com
url:                 http://clarkbk.com

# About
author:
  email:             tzidar@gmail.com
  name:              Tom Zidar
  social_urls:
    facebook:        https://www.facebook.com/tzidar
    github:          https://github.com/tzidar
    linkedin:        https://www.linkedin.com/in/tom-zidar-69087b45
    twitter:         https://twitter.com/tomzidar
    google_plus:     https://plus.google.com/u/0/101356415299525876294


# i delted this line  (under permalink)
# relative_permalinks: true